Repository nginxinc/nginx-hugo-theme, pull requests merged in 2025-02, with the labels that each got.

#128 Added scroller to sidebar
  assets/css/v2/style.css
  layouts/partials/sidebar-v2.html
Labels: bug

#138 Hde the v1 codeblocks on new theme + fix padding on v2 codeblocks
  assets/css/v2/style.css
  layouts/_default/_markup/render-codeblock.html
  layouts/_default/baseof.html
Labels: bug

#141 fix: toc not rendering correctly
  layouts/_default/_markup/render-codeblock.html
  layouts/partials/toc.html
Labels: bug

#144 Linted all existing files using biome
  assets/css/v2/style.css
  assets/js/code-copy.js
  assets/js/coveo.js
  assets/js/product-selector.js
  assets/js/sidebar-v2.js
  assets/js/sidebar.js
  assets/js/site-dropdown.js
  biome.json
Labels: cleanup

#145 Tooling: Add setup-pre-commit make target
  CONTRIBUTING.md
  Makefile
Labels: enhancement

#146 CI: Add commit and biome lint to CI
  .github/workflows/biome-lint.yml
  .github/workflows/commit-lint.yml
Labels: enhancement

#150 Tooling: Use correct go version syntax
  .github/workflows/hugo-build-test.yml
Labels: bug

#152 Add Qualtrics to Staging
  biome.json
  layouts/partials/qualtrics-feedback.html
Labels: bug, enhancement

#151 CI: Add github action to build documentation repo
  .github/workflows/hugo-build-test.yml
  .github/workflows/nginx-documentation-build.yml
Labels: enhancement

#154 Basic Redocly integreation in Mainframe
  assets/css/v2/style.css
  layouts/_default/baseof.html
Labels: bug
