Repository nginxinc/nginx-hugo-theme, pull requests merged in 2025-09, with the labels that each got.

#381 Fix sort and filter rendering on mobile for coveo
  assets/css/v2/style.css
Labels: bug

#383 Callouts: Prevent codeblocks overflowing callouts
  assets/css/v2/style.css
Labels: bug

#392 Lock scroll when coveo filter modal is open
  assets/css/v2/style.css
Labels: bug

#410 Replace usages of article .Title with .LinkTitle
  exampleSite/content/test-product/commerical/commercial-feature.md
  exampleSite/content/test-product/commerical/partial-commercial-feature.md
  layouts/partials/breadcrumb.html
  layouts/partials/sidebar-list-pages.html
  layouts/partials/sidebar-list.html
Labels: enhancement

#414 Refactor util and constant files into folders
  tests/src/cards.spec.js
  tests/src/constants/constants.js
  tests/src/constants/index.js
  tests/src/footer.spec.js
  tests/src/header.spec.js
  tests/src/product-landing.spec.js
  tests/src/sidebar.spec.js
  tests/src/tabs.spec.js
  tests/src/utils/index.js
  tests/src/utils/utils.js
Labels: cleanup
