Repository nginxinc/nginx-hugo-theme, pull requests merged in 2025-08, with the labels that each got.

#340 Add new product category facet to coveo
  layouts/partials/coveo-atomic.html
Labels: enhancement

#343 Update product icons + remove icon PNG files
  layouts/shortcodes/card.html
  static/images/icons/NGINX-Agent-product-icon.svg
  static/images/icons/NGINX-App-Protect-DoS-product-icon.png
  static/images/icons/NGINX-App-Protect-DoS-product-icon.svg
  static/images/icons/NGINX-App-Protect-WAF-product-icon.png
  static/images/icons/NGINX-App-Protect-WAF-product-icon.svg
  static/images/icons/NGINX-App-Protect-product-icon-RGB.svg
  static/images/icons/NGINX-Gateway-Fabric-product-icon.png
  static/images/icons/NGINX-Gateway-Fabric-product-icon.svg
  static/images/icons/NGINX-Ingress-Controller-product-icon.png
  static/images/icons/NGINX-Ingress-Controller-product-icon.svg
  static/images/icons/NGINX-Instance-Manager-product-icon.png
  static/images/icons/NGINX-Instance-Manager-product-icon.svg
  static/images/icons/NGINX-One-product-icon.png
  static/images/icons/NGINX-One-product-icon.svg
  static/images/icons/NGINX-Open-Source-product-icon.svg
  static/images/icons/NGINX-Plus-product-icon-RGB.png
  static/images/icons/NGINX-Plus-product-icon-RGB.svg
  static/images/icons/NGINX-Plus-product-icon.svg
  static/images/icons/NGINX-Unit-product-icon-RGB.png
  static/images/icons/NGINX-Unit-product-icon.svg
  static/images/icons/NGINX-WAF-product-icon-RGB.png
  static/images/icons/NGINX-WAF-product-icon-RGB.svg
  static/images/icons/NGINX-product-icon.png
  static/images/icons/NGINX-product-icon.svg
Labels: enhancement

#344 Fix icon width on safari
  assets/css/f5-hugo.css
Labels: bug

#352 Add even spacing to cards
  assets/css/v2/style.css
Labels: bug, cleanup

#357 Update release-build to only work if there is a full release
  .github/workflows/release-build.yml
Labels: enhancement

#364 List page issues
  layouts/_default/list.html
  layouts/partials/breadcrumb.html
Labels: bug

#367 ProductSelector: Open external links in a new tab
  exampleSite/data/product-selector.yaml
  layouts/partials/sidebar-v2.html
Labels: enhancement

#368 Fix coveo results would overflow on mobile
  assets/css/v2/style.css
  layouts/search/single.html
Labels: bug
